include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - avoid_relative_lib_imports
    - avoid_positional_boolean_parameters
    - avoid_renaming_method_parameters
    - avoid_unused_constructor_parameters
    - prefer_if_elements_to_conditional_expressions
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - use_named_constants
    - use_is_even_rather_than_modulo
    - unnecessary_string_interpolations
    - unnecessary_string_escapes
    - unnecessary_lambdas