name: vk_library
version: 1.0.1-doc.1
homepage: https://github.com/swedesjs/vk_library
description: "Library for interacting with VKAPI"

environment:
  sdk: ">=2.14.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.11.1

dependencies:
  dio: ^4.0.0
