name: vk_library
description: VK SDK for Dart supporting all public methods of VK api, group longpoll, etc
version: 1.0.3
repository: https://github.com/swedesjs/vk_library
homepage: https://github.com/swedesjs/vk_library

environment:
  sdk: '>=2.16.0 <3.0.0'

dev_dependencies:
  test: ^1.16.0
  json_serializable: ^6.1.5
  build_runner: ^2.1.8
  pedantic: ^1.11.1
dependencies:
  dio: ^4.0.4
  json_annotation: ^4.4.0
