name: vk_library
version: 1.0.2
homepage: https://github.com/swedesjs/vk_library
description: Library for working with VK api. In the future, there will be support for LongPoll, Uploading documents, and all sorts of different utilities.
issue_tracker: https://github.com/swedesjs/vk_library/issues

environment:
  sdk: ">=2.14.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.19.3

dependencies:
  dio: ^4.0.0
  path: ^1.8.0
  yaml: ^3.1.0
